# this is maintain by github.com/nonepork
# i know this is not really that "vim", but the control flow is different.
# =================================================================================================
# global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'l']
quit = ['q'] # also know as, theprimeagen troller
# movement
list_up = ['k', '']
list_down = ['j', '']
page_up = ['c', '']
page_down = ['', '']
# file panel control
create_new_file_panel = ['', '']
close_file_panel = ['', '']
next_file_panel = ['', '']
previous_file_panel = ['', '']
toggle_file_preview_panel = ['', '']
open_sort_options_menu = ['', '']
toggle_reverse_sort = ['', '']
# change focus
focus_on_process_bar = ['', '']
focus_on_sidebar = ['', '']
focus_on_metadata = ['', '']
# create file/directory and rename
file_panel_item_create = ['', '']
file_panel_item_rename = ['r', '']
# file operations
copy_items = ['y', '']
cut_items = ['x', '']
paste_items = ['p', '']
delete_items = ['d', '']
# compress and extract
extract_file = ['', '']
compress_file = ['', '']
# editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['e', '']
# other
pinned_directory = ['', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['', '']
open_help_menu = ['?', '']
open_command_line = [':', '']
copy_path = ['y', '']
copy_present_working_directory = ['', '']
toggle_footer = ['', '']
# =================================================================================================
# typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', '']
cancel_typing = ['esc', '']
# =================================================================================================
# normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['h', '']
search_bar = ['i', '']
# =================================================================================================
# select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['', '']
file_panel_select_mode_items_select_up = ['', '']
file_panel_select_all_items = ['', '']