cursor #cdd6f4
cursor_text_color #a6adc8

foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #1e1e2e
selection_background  #b4befe
url_color             #cba6f7

color0   #181825
color1   #ea5d77
color2   #40b95c
color3   #ffce3f
color4   #cfa7ff
color5   #f0e4ff
color6   #cba6f7
color7   #434245
color8   #cfccd1
color9   #ff7f97
color10  #72ff92
color11  #ffd14c
color12  #cda3ff
color13  #f0e4ff
color14  #e8d5ff
color15  #fcf9ff
